config/routes.rb
Rails.application.routes.draw do
  resources :blurbs
  resources :pop_up_categories do
    member do
      get :contract
      get :expand
    end
  end
  resources :categories do
    collection do
      get :list_with_features
      get :list_with_shapes
      get :list
      get :all
      get :add_curator
      get :all_with_features
      get :all_with_shapes
      match '/by_title/:title.:format' => 'categories#by_title'
    end
    member do
      get :list_with_features
      put :update_primary_description
      get :list_with_shapes
      get :detailed
      get :set_primary_description
      get :list
      get :all
      get :all_with_features
      get :all_with_shapes
      get :modify_title
    end
    resources :children, :controller => 'categories' do
      collection do
        get :add_curator
      end
      member do
        get :contract
        get :expand
        get :modify_title
        get :expanded
        get :contracted
      end
    end
    resources :iframe, :controller => 'categories' do
      collection do
        get :add_curator
      end
      member do
        get :contract
        get :expand
        get :modify_title
      end
    end
    resources :translated_titles do
      collection do
        get :add_author
      end    
    end
    resources :descriptions do
      collection do
        get :add_author
      end
      member do
        get :contract
        get :expand
      end
      resources :sources do
        member do
          get :contract
          get :expand
        end
        resources :translated_sources do
          collection do
            get :add_author
          end
        end
      end
    end
    resources :sources do
      member do
        get :contract
        get :expand
      end
      resources :translated_sources do
        collection do
          get :add_author
        end     
      end
    end
  end
  root :to => 'home#index'
  resources :places, :only => 'show'
  resources :media, :only => 'show', :path => 'media_objects'
  # match '/:controller(/:action(/:id))'
end

app/models/source.rb
# == Schema Information
#
# Table name: sources
#
#  id            :integer          not null, primary key
#  resource_id   :integer
#  resource_type :string(255)
#  mms_id        :integer
#  volume_number :integer
#  start_page    :integer
#  start_line    :integer
#  end_page      :integer
#  end_line      :integer
#  passage       :text
#  language_id   :integer          not null
#  note          :text
#  creator_id    :integer          not null
#  created_at    :datetime
#  updated_at    :datetime
#  oral          :string(255)
#  taken_on      :datetime
#

class Source < ActiveRecord::Base
  attr_accessible :mms_id, :oral, :volume_number, :start_page, :start_line, :end_page, :end_line, :language_id, :passage, :note, :taken_on
  
  validates_presence_of :resource_id, :resource_type
  #validates_presence_of :start_page
  validates_presence_of :language_id, :creator_id
  validate :mms_id_or_oral
  belongs_to :resource, :polymorphic => true 
  belongs_to :creator, :class_name => 'AuthenticatedSystem::User', :foreign_key => 'creator_id'
  belongs_to :language, :class_name => 'ComplexScripts::Language'
  has_many :translated_sources, :dependent => :destroy
  
  def formatted
    if mms_id.blank?
      str = "#{Source.human_attribute_name(:oral).s}: #{self.oral}"
      str << " (#{self.taken_on.to_date.to_formatted_s(:long)})" if !self.taken_on.nil?
      return str
    end
    str = "#{Source.human_attribute_name(:mms_id).s} \##{self.mms_id}" 
    pages_str = self.start_page.to_s
    if !self.start_line.nil?
      pages_str << ".#{self.start_line}"
    end
    if !self.end_page.nil? or !self.end_line.nil?
      pages_str << '-'
      if !self.end_page.nil?
        pages_str << self.end_page.to_s
      end
      if !self.end_line.nil?
        pages_str << ".#{self.end_line}."
      end
    end
    str << ", #{pages_str}" if !pages_str.blank?
    return str
  end
  
  private
  
  def mms_id_or_oral
    if !(mms_id.blank? ^ oral.blank?)
      errors[:base] << 'Specify either an MMS ID or an oral source, but not both'
    end
  end
end

app/controllers/sources_controller.rb
class SourcesController < AclController
  before_filter :find_category
  respond_to :html, :xml, :js
   
  def initialize
     super
     @guest_perms += [ 'sources/expand', 'sources/contract']
   end  
  
  # GET /sources
  # GET /sources.xml
  def index
    redirect_to category_child_url(@main_category,@category)
  end

  # GET /sources/1
  # GET /sources/1.xml
  def show
    redirect_to category_child_url(@main_category,@category)
  end

  # GET /sources/new
  # GET /sources/new.xml
  def new
    @languages = ComplexScripts::Language.order('title')
    @source = Source.new(:language_id => ComplexScripts::Language.find_by_code('eng').id)
    if params[:description_id].nil?
      @description = nil
      @source.resource = @category
    else
      @description = Description.find(params[:description_id])
      @source.resource = @description
    end
    respond_with @source
  end

  # GET /sources/1/edit
  def edit
    @languages = ComplexScripts::Language.order('title')
    if params[:description_id].nil?
      @description = nil
    else
      @description = Description.find(params[:description_id])
    end
    @source = Source.find(params[:id])
    respond_with(@source)
  end

  # POST /sources
  # POST /sources.xml
  def create
    @source = Source.new(params[:source])
    @languages = ComplexScripts::Language.order('title')
    if params[:description_id].nil?
      @description = nil
      @source.resource = @category
    else
      @description = Description.find(params[:description_id])
      @source.resource = @description
    end
    @source.creator = current_user
    respond_to do |format|
      if @source.save
        format.html do
          flash[:notice] = 'Source was successfully created.'
			    if @category != @main_category 
			      redirect_to category_child_url(@main_category, @category)
			    else
			      redirect_to(@category)
			    end		
        end
        format.js   { render 'categories/show' }
        format.xml  { render :xml => @source, :status => :created, :location => @source }
      else
        format.html { render 'new' }
        format.js   { render 'new' }
        format.xml  { render :xml => @source.errors, :status => :unprocessable_entity }        
      end
    end
  end

  # PUT /sources/1
  # PUT /sources/1.xml
  def update
    @source = Source.find(params[:id])
    @languages = ComplexScripts::Language.order('title')
    if params[:description_id].nil?
      @description = nil
      @source.resource = @category
    else
      @description = Description.find(params[:description_id])
      @source.resource = @description
    end
    respond_to do |format|
      if @source.update_attributes(params[:source])
        format.html do
          flash[:notice] = 'Source was successfully updated.'
			    if @category != @main_category 
			      redirect_to category_child_url(@main_category, @category)
			    else
			      redirect_to(@category)
			    end		
        end
        format.js   { render 'categories/show' }
        format.xml  { head :ok }
      else
        format.html { render 'edit' }
        format.js   { render 'edit' }
        format.xml  { render :xml => @source.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sources/1
  # DELETE /sources/1.xml
  def destroy
    @source = Source.find(params[:id])
    @source.destroy

    respond_to do |format|
      format.html do
		    if @category != @main_category 
		      redirect_to category_child_url(@main_category, @category)
		    else
		      redirect_to(@category)
		    end          
	    end
      format.js   { render 'categories/show' }
      format.xml  { head :ok }
    end
  end

  def contract
     @source = Source.find(params[:id])
     if !params[:description_id].nil?
       @resource = Description.find(params[:description_id])
     else
       @resource = @category
     end
  end # renders contract.js.erb
  
  def expand
    @source = Source.find(params[:id])
    #if !params[:description_id].nil?
    if @source.resource_type == 'Category'
      @resource = @category
    else #'Description'
      @resource = Description.find(@source.resource_id)
    end
    render 'index' # .js.erb
  end
  
  private
  # This is tied to categories
  def find_category
    @category = Category.find(params[:category_id])
	  @main_category = @category.application_root
  end
    
  def source_url(source)
    category_source_url(@category, source)
  end    
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/views/sources/_contracted.html.erb
<% if source.resource_type == 'Category'
     edit_path = edit_category_source_path(resource, source)
     expand_path = expand_category_source_path(resource, source)
     hash_path = hash_for_edit_category_source_path
     new_translated_path = new_category_source_translated_source_path(resource, source)
     hash_translated_path = hash_for_new_category_source_translated_source_path
   else
     edit_path = edit_category_description_source_path(resource.category, resource, source)
     expand_path = expand_category_description_source_path(resource.category, resource, source)
     hash_path = hash_for_edit_category_description_source_path
     new_translated_path = new_category_description_source_translated_source_path(resource.category, resource, source)
     hash_translated_path = hash_for_new_category_description_source_translated_source_path
   end %>
   <p>
<%=  link_to '&nbsp;'.html_safe, expand_path, :remote => true, :class => 'descriptionplus_icon' %>
<%=  authorized?(hash_path) ? link_to(source.formatted, edit_path, :remote => true) : source.formatted %>
<%   if source.language.code[0..1] != I18n.locale.to_s %>
       (<%= source.language.title.s %>)
<%   end
     if authorized? hash_translated_path %>
<%=    form_tag new_translated_path, :method => :get, :remote => true do %>
<%=      submit_tag te('add.record', :what => TranslatedSource.model_name.human) %>
<%     end 
     end %>
   </p>

app/views/sources/_edit.html.erb
<% if @description.nil? %>
<%   source_path = category_source_path(@category, @source) %>
<%   hash_destroy_path = hash_for_category_source_path(:action => 'destroy') %>
     <h1><%= ts :for, :what => t('edit.ing.record', :what => Source.model_name.human.capitalize), :whom => "<em>#{h(@category.title)}</em>" %></h1>
<% else %>
<%   source_path = category_description_source_path(@category,@description, @source) %>
<%   hash_destroy_path = hash_for_category_description_source_path(:action => 'destroy') %>
     <h1><%= ts :for, :what => t('edit.ing.record', :what => Source.model_name.human.capitalize),:whom => Description.model_name.human.capitalize %></h1>
<% end %>
<%= error_messages_for :source %>
<%= form_for(:source, :url => source_path, :remote => true, :method => :put, :html => { :id => 'source_form' }) do |f| %>
<%=   render :partial => 'form', :locals => {:f => f} %>
      <p><%= globalized_submit_tag 'update.this' %></p>
<%  end %>
<%= javascript_tag("$(\'#source_form\').bind(\'ajax:beforeSend\', function(){ tinyMCE.triggerSave();});") %>
<p>
<% if authorized? hash_destroy_path %>
<%=  link_to ts('delete.this'), source_path, :remote => true, :confirm => 'Are you sure?', :method => :delete %> |
<% end %>
<%= link_to ts('cancel.this'), category_child_path(@main_category, @category), :remote => true %>
</p>

app/views/sources/_expanded.html.erb
<% if source.resource_type == 'Category'
     edit_path = edit_category_source_path(resource, source)
     contract_path = contract_category_source_path(resource, source)
     hash_path = hash_for_edit_category_source_path
     new_translated_path = new_category_source_translated_source_path(resource, source)
     hash_translated_path = hash_for_new_category_source_translated_source_path
   else
     edit_path = edit_category_description_source_path(category, resource, source)
     contract_path = contract_category_description_source_path(category, resource, source)
     hash_path = hash_for_edit_category_description_source_path
     new_translated_path = new_category_description_source_translated_source_path(category, resource, source)
     hash_translated_path = hash_for_new_category_description_source_translated_source_path
   end %>
   <p>
<%=  link_to '&nbsp;'.html_safe, contract_path, :remote => true, :class => 'descriptionminus_icon' %>
<%=  authorized?(hash_path) ? link_to(source.formatted, edit_path, :remote => true) : source.formatted %>
<%   if source.language.code[0..1] != I18n.locale.to_s %>
       (<%= source.language.title.s %>)
<%   end %>
<%   if authorized? hash_translated_path 
	   form_tag new_translated_path, :method => :get, :remote => true do %>
<%=      submit_tag te('add.record', :what => TranslatedSource.model_name.human) %>
<%     end 
     end %>
   </p>
<%= display_if_not_blank Source.human_attribute_name(:passage).s, source.passage %>
<%= display_if_not_blank Source.human_attribute_name(:note).s, source.note %>
<%  if !source.translated_sources.empty? %>
	  <p><b><%= TranslatedSource.model_name.human(:count => :many) %>:</b>
<%      if source.resource_type == 'Category' %> 
<%=       ( source.translated_sources.collect { |t| "#{t.title.s} (#{authorized?(hash_for_edit_category_source_translated_source_path) ? link_to("<i>#{t.language.title.s}#{"#{", from #{join_with_and(t.authors.collect{|a| a.fullname})}" if !t.authors.empty?}"}</i>", edit_category_source_translated_source_path(category,source, t), :remote => true)  : "<i>#{t.language.title.s}#{"#{", from #{join_with_and(t.authors.collect{|a| a.fullname})}" if !t.authors.empty?}"}</i>"})" }).join(', ') %>		 
<%      else %>
<%=       ( source.translated_sources.collect { |t| "#{t.title.s} (#{authorized?(hash_for_edit_category_description_source_translated_source_path) ? link_to("<i>#{t.language.title.s}#{"#{", from #{join_with_and(t.authors.collect{|a| a.fullname})}" if !t.authors.empty?}"}</i>", edit_category_description_source_translated_source_path(category,resource,source, t), :remote => true)  : "<i>#{t.language.title.s}#{"#{", from #{join_with_and(t.authors.collect{|a| a.fullname})}" if !t.authors.empty?}"}</i>"})" }).join(', ') %>	
<%      end %>
      </p>
<%  end %>

app/views/sources/_form.html.erb
<%= tagged_tinymce_script %>
<p><b><%= Source.human_attribute_name('mms_id').s %></b><br />
  <%= f.text_field :mms_id %>
</p>
<p><b><%= Source.human_attribute_name('oral').s %> (Person's Name)</b><br />
  <%= f.text_field :oral %>
</p>
<p><b><%= Source.human_attribute_name('taken_on').s %></b><br />
  <%= f.datetime_select :taken_on, :include_blank => true %>
</p>
<p><b><%= Source.human_attribute_name('volume_number').s %></b><br />
  <%= f.text_field :volume_number %>
</p>
<p><b><%= Source.human_attribute_name('start_page').s %></b><br />
	<%= f.text_field :start_page %>
</p>
<p><b><%= Source.human_attribute_name('start_line').s %></b><br />
	<%= f.text_field :start_line %>
</p>
<p><b><%= Source.human_attribute_name('end_page').s %></b><br />
	<%= f.text_field :end_page %>
</p>
<p><b><%= Source.human_attribute_name('end_line').s %></b><br />
	<%= f.text_field :end_line %>
</p>
<p>
    <b><%= Source.human_attribute_name('language_id').s %></b><br />
<%= f.select(:language_id, @languages.collect {|l| [ h(l.title), l.id ] }, { :include_blank => false }) %>
</p>
<p><b><%= Source.human_attribute_name('passage').s %></b><br />
<%= f.text_area :passage, :rows => 16, :cols => 40, :class => 'mceEditor' %>
</p>
<p><b><%= Source.human_attribute_name('note').s %></b><br />
<%= f.text_area :note, :rows => 16, :cols => 40, :class => 'mceEditor' %>
</p>
<div id="update_div"></div>

app/views/sources/_index.html.erb
<p><b>Detail for sources:</b></p>
<%   resource.sources.all.each do |s| %>
	   <div id="<%= "#{s.id}_sourcediv" %>">
<%     if @source.nil? 	%>	
<%=      render :partial => 'sources/contracted', :locals => {:resource => resource, :source => s} %>
<%     else %>
<%       if s == @source %>
<%=        render :partial => 'sources/expanded', :locals => {:resource => resource, :source => s, :category => defined?(category) ? category : resource } %>
<%	     else %>
<%=        render :partial => 'sources/contracted', :locals => {:resource => resource, :source => s} %>
<%       end %>
<%     end %>
       </div>
<%   end %>

app/views/sources/_new.html.erb
<% if @description.nil? %>
<%   path = category_sources_path(@category) %>
     <h1><%= ts :for, :what => Source.model_name.human.capitalize, :whom => "<em>#{h(@category.title)}</em>" %></h1>
<% else %>
<%   path = category_description_sources_path(@category, @description) %>
     <h1><%= ts :for, :what => Source.model_name.human.capitalize, :whom => Description.model_name.human %></h1>
<% end %>
<%= error_messages_for :source %>
<%= form_for(:source, :url => path, :html => { :id => 'source_form' }) do |f| %>
<%=   render :partial => 'form', :locals => {:f => f} %>
      <p><%= submit_tag te('creat.e.record', :what => Source.model_name.human.capitalize), language_options(:disable_with => 'Processing...') %></p>
<%  end %>
<%= javascript_tag("$(\'#source_form\').bind(\'ajax:beforeSend\', function(){ tinyMCE.triggerSave();});") %>
<p>
<%= link_to ts('cancel.this'), category_child_path(@main_category, @category), :remote => true %>
</p>

app/views/sources/contract.js.erb
$("#<%= @source.id %>_sourcediv").html("<%= escape_javascript(render(:partial => 'contracted', :locals => {:resource => @resource, :source => @source})) %>")

app/views/sources/edit.html.erb
<%= render :partial => 'edit' %>

app/views/sources/index.js.erb
$("#<%= @resource.instance_of?(Description) ? 'descsources' : 'catsources' %>_div").html("<%= escape_javascript(render(:partial => 'sources/index', :locals => { :resource => @resource, :category => @category })) %>")

app/views/sources/new.html.erb
<%= render :partial => 'new' %>

app/views/sources/new.js.erb
$("#info").html("<%= escape_javascript(render(:partial => 'new')) %>")