config/routes.rb
Rails.application.routes.draw do
  resources :blurbs
  resources :pop_up_categories do
    member do
      get :contract
      get :expand
    end
  end
  resources :categories do
    collection do
      get :list_with_features
      get :list_with_shapes
      get :list
      get :all
      get :add_curator
      get :all_with_features
      get :all_with_shapes
      match '/by_title/:title.:format' => 'categories#by_title'
    end
    member do
      get :list_with_features
      put :update_primary_description
      get :list_with_shapes
      get :detailed
      get :set_primary_description
      get :list
      get :all
      get :all_with_features
      get :all_with_shapes
      get :modify_title
    end
    resources :children, :controller => 'categories' do
      collection do
        get :add_curator
      end
      member do
        get :contract
        get :expand
        get :modify_title
        get :expanded
        get :contracted
      end
    end
    resources :iframe, :controller => 'categories' do
      collection do
        get :add_curator
      end
      member do
        get :contract
        get :expand
        get :modify_title
      end
    end
    resources :translated_titles do
      collection do
        get :add_author
      end    
    end
    resources :descriptions do
      collection do
        get :add_author
      end
      member do
        get :contract
        get :expand
      end
      resources :sources do
        member do
          get :contract
          get :expand
        end
        resources :translated_sources do
          collection do
            get :add_author
          end
        end
      end
    end
    resources :sources do
      member do
        get :contract
        get :expand
      end
      resources :translated_sources do
        collection do
          get :add_author
        end     
      end
    end
  end
  root :to => 'home#index'
  resources :places, :only => 'show'
  resources :media, :only => 'show', :path => 'media_objects'
  # match '/:controller(/:action(/:id))'
end

app/models/translated_title.rb
# == Schema Information
#
# Table name: translated_titles
#
#  id          :integer          not null, primary key
#  title       :string(255)      not null
#  language_id :integer          not null
#  category_id :integer          not null
#  creator_id  :integer          not null
#  created_at  :datetime
#  updated_at  :datetime
#

class TranslatedTitle < ActiveRecord::Base
  attr_accessible :language_id, :title, :author_ids
  validates_presence_of :title, :language_id, :category_id, :creator_id
  validates_uniqueness_of :language_id, :scope => :category_id
  belongs_to :language, :class_name => 'ComplexScripts::Language'
  belongs_to :creator, :class_name => 'AuthenticatedSystem::User', :foreign_key => 'creator_id'
  belongs_to :category
  has_and_belongs_to_many :authors, :class_name => 'AuthenticatedSystem::Person', :join_table => 'authors_translated_titles', :association_foreign_key => 'author_id'
  accepts_nested_attributes_for :authors
end

app/controllers/translated_titles_controller.rb
class TranslatedTitlesController < AclController
  before_filter :find_category
  cache_sweeper :translated_title_sweeper, :only => [:create, :update, :destroy]
  respond_to :html, :xml, :js
  
  # GET /translated_titles
  # GET /translated_titles.xml
  def index
    @translated_titles = @category.translated_titles
    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @translated_titles }
    end
  end

  # GET /translated_titles/1
  # GET /translated_titles/1.xml
  def show
    @translated_title = TranslatedTitle.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @translated_title }
    end
  end

  # GET /translated_titles/new
  # GET /translated_titles/new.xml
  def new
    # TODO: for now default to tibetan, in the future make this more complicated!
    @translated_title = TranslatedTitle.new(:language_id => ComplexScripts::Language.find_by_code('bod').id)
    @languages = ComplexScripts::Language.order('title')
    @authors = AuthenticatedSystem::Person.order('fullname')
    respond_with @translated_title
  end

  # GET /translated_titles/1/edit
  def edit
    @translated_title = TranslatedTitle.find(params[:id])
    @languages = ComplexScripts::Language.order('title')
    @authors = AuthenticatedSystem::Person.order('fullname')    
  end # edit.js.erb

  # POST /translated_titles
  # POST /translated_titles.xml
  def create
    @translated_title = @category.translated_titles.new(params[:translated_title])
    @translated_title.creator = current_user
    respond_to do |format|
      if @translated_title.save
        flash[:notice] = 'TranslatedTitle was successfully created.'
	      format.html do
		      if @category != @main_category 
		        redirect_to category_child_url(@main_category, @category)
		      else
		        redirect_to(@category)
		      end		  	
	      end
        format.js   { render 'categories/show' }
		    format.xml  { render :xml => @translated_title, :status => :created, :location => @translated_title }		
      else
        @languages = ComplexScripts::Language.order('title')
        @authors = AuthenticatedSystem::Person.order('fullname')                
        format.html { render 'new' }
        format.js   { render 'new' }
        format.xml  { render :xml => @translated_title.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /translated_titles/1
  # PUT /translated_titles/1.xml
  def update
    params[:translated_title][:author_ids] ||= []
    @translated_title = TranslatedTitle.find(params[:id])
    @authors = AuthenticatedSystem::Person.order('fullname')    
	  respond_to do |format|	
      if @translated_title.update_attributes(params[:translated_title])
        flash[:notice] = 'TranslatedTitle was successfully updated.'
        format.html do
	        if @category != @main_category # if request.xhr?
	          redirect_to category_child_url(@main_category, @category)
	        else
	          redirect_to(@category)
	        end
	      end
	      format.js   { render 'categories/show' }
	      format.xml  { head :ok }
      else
        @languages = ComplexScripts::Language.order('title')	
        format.html { render 'edit' }
        format.js   { render 'edit' }
        format.xml  { render :xml => @translated_title.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /translated_titles/1
  # DELETE /translated_titles/1.xml
  def destroy
    @translated_title = TranslatedTitle.find(params[:id])
    @translated_title.destroy
    respond_to do |format|
      format.html do
	      if @category != @main_category 
	        redirect_to category_child_url(@main_category, @category)
	      else
	        redirect_to(@category)
	      end          
      end
      format.js   { render 'categories/show' }
      format.xml  { head :ok }
    end
  end

  def add_author
    @authors = AuthenticatedSystem::Person.order('fullname')
  end # add_author.js.erb
  
    
  private
  # This is tied to categories, but once other titles are translated it can get disentangled through request.request_uri
  def find_category
    @category = Category.find(params[:category_id])
	  @main_category = @category.application_root
  end
  
  def translated_title_url(title)
    category_translated_title_url(@category, title)
  end
  
 
end

app/helpers/translated_titles_helper.rb
module TranslatedTitlesHelper
end

app/views/translated_titles/_authors_selector.erb
<div class="dropdown">
<p>
<%= select_tag 'translated_title[author_ids][]', options_for_select(@authors.collect{|a| [ a.fullname , a.id] }, selected.nil? ? nil : selected) %>
<%= link_to_function 'remove', "this.up('.dropdown').remove()" %>
</p>
</div>

app/views/translated_titles/_authors_selector.html.erb
<div class="dropdown">
<p>
<%= select_tag 'translated_title[author_ids][]', options_for_select(@authors.collect{|a| [ a.fullname , a.id] }, selected.nil? ? nil : selected) %>
<%= link_to_function ts(:remove), "$(this).parents('.dropdown:first').remove()" %>
</p>
</div>

app/views/translated_titles/_edit.html.erb
<h1><%= ts :in, :what => t(:for, :what => t('edit.ing.record', :what => TranslatedTitle.model_name.human.titleize), :whom => "<em>#{h(@category.title)}</em>"), :where => h(@translated_title.language.title) %></h1>
<%= error_messages_for :translated_title %>
<%= form_for(:translated_title, :url => category_translated_title_path(@category, @translated_title), :remote => true, :method => :put, :html => { :id => 'translated_title_form' }) do |f| %>
<%=   render :partial => 'translated_titles/form', :locals => {:f => f} %>
      <p><div id="update_div">
<%=   submit_tag 'update translation', :disable_with => 'Processing...' %>
      </div></p>
<%  end %>
<p>
<%  if authorized? hash_for_category_translated_title_path(:action => 'destroy') %>
<%=   link_to ts('delete.this'), category_translated_title_path(@category, @translated_title), :remote => true, :confirm => 'Are you sure?', :method => :delete %> |
<%  end %>
<%= link_to ts('cancel.this'), category_child_path(@main_category, @category), :remote => true %>
</p>

app/views/translated_titles/_form.html.erb
<p>
    <b><%= TranslatedTitle.human_attribute_name(:language_id).s %></b><br />
<%= f.select(:language_id, @languages.collect {|l| [ h(l.title), l.id ] }, { :include_blank => false }) %>
</p>
<p>
    <b><%= TranslatedTitle.model_name.human.titleize.s %></b><br />
<%= f.text_field :title, fixed_language_options(:lang => @translated_title.language.code) %>
</p>
<p>
<%= link_to ts('add.record', :what => t('new.record', :what => TranslatedTitle.human_attribute_name(:author))), add_author_category_translated_titles_path(@category), :remote => true %>
</p>
<div id="authors_div">
<% if @translated_title.authors.empty? && !current_user.person.nil? %>
<%=  render :partial => 'authors_selector', :locals => {:selected => current_user.person_id} %>
<% else
     for author in @translated_title.authors %>
<%=    render :partial => 'authors_selector', :locals => {:selected => author.id} %>
<%   end
   end %>
</div>

app/views/translated_titles/_new.html.erb
<h1><%= ts :for, :what => t('translat.ion').capitalize, :whom => "<em>#{h(@category.title)}</em>" %></h1>
<%= error_messages_for :translated_title %>
<%= form_for(:translated_title, :url => category_translated_titles_path(@category), :remote => true, :html => { :id => 'translated_title_form' }) do |f| %>
<%=   render :partial => 'translated_titles/form', :locals => {:f => f} %>
      <div id="update_div"></div>
      <p><%= submit_tag te('creat.e.record', :what => t('translat.ion')), :disable_with => 'Processing...' %></p>
<%  end %>
<p>
<%= link_to ts('cancel.this'), category_child_path(@main_category, @category), :remote => true %>
</p>

app/views/translated_titles/add_author.js.erb
$("#update_div").before("<%= escape_javascript(render(:partial => 'authors_selector', :locals => {:selected => nil})) %>")

app/views/translated_titles/edit.html.erb
<h1><%= ts :in, :what => t(:for, :what => t('edit.ing.record', :what => TranslatedTitle.model_name.human.titleize), :whom => "<em>#{h(@category.title)}</em>"), :where => h(@translated_title.language.title %></h1>
<%= error_messages_for :translated_title %>
<%= form_for(:translated_title, :url => category_translated_title_path(@category, @translated_title), :method => :put) do |f| %>
<%=   render :partial => 'form', :locals => {:f => f} %>
      <p><%= f.submit 'Update' %></p>
<%  end %>
<p>
<% if authorized? hash_for_category_translated_title_path(:action => 'destroy') %>
<%=  link_to 'Delete', category_translated_title_path(@category, @translated_title), :confirm => 'Are you sure?', :method => :delete %> |
<% end %>
<%= link_to ts('cancel.this'), @category %>
</p>

app/views/translated_titles/index.html.erb
<h1>Listing translated_titles</h1>

<table class="normal">
  <tr>
    <th>Title</th>
    <th>Language</th>
  </tr>

<% for translated_title in @translated_titles %>
  <tr>
    <td><%=h translated_title.title %></td>
    <td><%=h translated_title.language_id %></td>
    <td><%= link_to 'Show', category_translated_title_path(@category, translated_title) %></td>
    <td><%= link_to 'Edit', edit_category_translated_title_path(@category, translated_title) %></td>
    <td><%= link_to 'Destroy', category_translated_title_path(@category, translated_title), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<p>
<%= link_to 'New translated_title', new_category_translated_title_path(@category) %>
</p>

app/views/translated_titles/new.html.erb
<h1><%= ts :for, :what => t('translat.ion').capitalize, :whom => "<em>#{h(@category.title)}</em>" %></h1>
<%= error_messages_for :translated_title %>
<%= form_for(:translated_title, :url => category_translated_titles_path(@category)) do |f| %>
<%=   render :partial => 'form', :locals => {:f => f} %>
      <p><%= f.submit te('creat.e.record', :what => TranslatedTitle.model_name.human) %></p>
<%  end %>
<p><%= link_to ts('cancel.this'), @category %></p>

app/views/translated_titles/new.js.erb
$("#info").html("<%= escape_javascript(render(:partial => 'new')) %>")

app/views/translated_titles/show.html.erb
<p>
  <b>Title:</b>
  <%=h @translated_title.title %>
</p>

<p>
  <b>Language:</b>
  <%=h @translated_title.language_id %>
</p>


<%= link_to 'Edit', edit_translated_title_path(@translated_title) %> |
<%= link_to 'Back', translated_titles_path %>