config/routes.rb
Rails.application.routes.draw do
  resources :blurbs
  resources :pop_up_categories do
    member do
      get :contract
      get :expand
    end
  end
  resources :categories do
    collection do
      get :list_with_features
      get :list_with_shapes
      get :list
      get :all
      get :add_curator
      get :all_with_features
      get :all_with_shapes
      match '/by_title/:title.:format' => 'categories#by_title'
    end
    member do
      get :list_with_features
      put :update_primary_description
      get :list_with_shapes
      get :detailed
      get :set_primary_description
      get :list
      get :all
      get :all_with_features
      get :all_with_shapes
      get :modify_title
    end
    resources :children, :controller => 'categories' do
      collection do
        get :add_curator
      end
      member do
        get :contract
        get :expand
        get :modify_title
        get :expanded
        get :contracted
      end
    end
    resources :iframe, :controller => 'categories' do
      collection do
        get :add_curator
      end
      member do
        get :contract
        get :expand
        get :modify_title
      end
    end
    resources :translated_titles do
      collection do
        get :add_author
      end    
    end
    resources :descriptions do
      collection do
        get :add_author
      end
      member do
        get :contract
        get :expand
      end
      resources :sources do
        member do
          get :contract
          get :expand
        end
        resources :translated_sources do
          collection do
            get :add_author
          end
        end
      end
    end
    resources :sources do
      member do
        get :contract
        get :expand
      end
      resources :translated_sources do
        collection do
          get :add_author
        end     
      end
    end
  end
  root :to => 'home#index'
  resources :places, :only => 'show'
  resources :media, :only => 'show', :path => 'media_objects'
  # match '/:controller(/:action(/:id))'
end

app/models/description.rb
# == Schema Information
#
# Table name: descriptions
#
#  id          :integer          not null, primary key
#  category_id :integer          not null
#  content     :text             default(""), not null
#  language_id :integer          not null
#  is_main     :boolean          default(FALSE), not null
#  creator_id  :integer          not null
#  created_at  :datetime
#  updated_at  :datetime
#  title       :string(255)
#



class Description < ActiveRecord::Base
  attr_accessible :category_id, :content, :language_id, :is_main, :title, :author_ids
  validates_presence_of :content, :category_id, :language_id, :creator_id
  belongs_to :language, :class_name => 'ComplexScripts::Language'
  belongs_to :creator, :class_name => 'AuthenticatedSystem::User', :foreign_key => 'creator_id'
  belongs_to :category  
  has_and_belongs_to_many :authors, :class_name => 'AuthenticatedSystem::Person', :join_table => 'authors_descriptions', :association_foreign_key => 'author_id' 
  has_many :sources, :as => :resource
  accepts_nested_attributes_for :authors
end

app/controllers/descriptions_controller.rb
class DescriptionsController < AclController
  before_filter :find_category
  cache_sweeper :description_sweeper, :only => [:create, :update, :destroy]
  respond_to :html, :xml, :js
   
  def initialize
     super
     @guest_perms += ['descriptions/expand', 'descriptions/contract']
   end  
  
  # GET /descriptions
  # GET /descriptions.xml
  def index
    redirect_to category_child_url(@main_category,@category)
    #@descriptions = @category.descriptions
    #respond_to do |format|
    #  format.xml
    #end
  end

  # GET /descriptions/1
  # GET /descriptions/1.xml
  def show
    redirect_to category_child_url(@main_category,@category)
    #@description = Description.find(params[:id])
    #respond_to do |format|
    #  format.xml # { render :xml => @description }
    #end
  end

  # GET /descriptions/new
  # GET /descriptions/new.xml
  def new
    default_language_id = session[:default_language_id]  || ComplexScripts::Language.find_by_locale(I18n.locale).id
    @description = @category.descriptions.new(:language_id => default_language_id)
    @languages = ComplexScripts::Language.order('title')
    @authors = AuthenticatedSystem::Person.order('fullname')
    respond_with @description
  end
  
  # GET /descriptions/1/edit
  def edit
    @description = Description.find(params[:id])
    @languages = ComplexScripts::Language.order('title')
    @authors = AuthenticatedSystem::Person.order('fullname')
  end

  # POST /descriptions
  # POST /descriptions.xml
  def create
    if @category.descriptions.empty?
      params[:description][:is_main] = "true"
    end
    @description = Description.new(params[:description])
    @description.creator = current_user
    respond_to do |format|
      if @description.save
        authors = @description.authors
        session[:default_author_id] = authors.first.id if authors.size==1
        session[:default_language_id] = @description.language.id
        format.html do
          flash[:notice] = 'Description was successfully created.'
		      if @category != @main_category
		        redirect_to category_child_url(@main_category, @category)
		      else
		        redirect_to(@category)
		      end
        end
        format.js { render 'categories/show' }
        format.xml  { render :xml => @description, :status => :created, :location => @description }
      else
        @languages = ComplexScripts::Language.order('title')
        @authors = AuthenticatedSystem::Person.order('fullname')
        format.html {render 'new'}
        format.js   {render 'new'}
        format.xml  { render :xml => @description.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /descriptions/1
  # PUT /descriptions/1.xml
  def update
    params[:description][:author_ids] ||= []
    @description = Description.find(params[:id])
    @authors = AuthenticatedSystem::Person.order('fullname')
    respond_to do |format|
      if @description.update_attributes(params[:description])
        flash[:notice] = 'Description was successfully updated.'
        format.html do
	        if @category != @main_category # if request.xhr?
	          redirect_to category_child_url(@main_category, @category)
	        else
	          redirect_to(@category)
	        end
	      end
	      format.js { render 'categories/show' }
	      format.xml  { head :ok }
      else
        @languages = ComplexScripts::Language.order('title')
        @authors = AuthenticatedSystem::Person.order('fullname')
        format.html { render 'edit' }
        format.js   { render 'edit' } #.js.erb
        format.xml  { render :xml => @description.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /descriptions/1
  # DELETE /descriptions/1.xml
  def destroy
    @description = Description.find(params[:id])
    @description.destroy
    respond_to do |format|
      format.html do
	      if @category != @main_category 
	        redirect_to category_child_url(@main_category, @category)
	      else
	        redirect_to(@category)
	      end          
      end      
      format.js   { render 'categories/show' }
      format.xml  { head :ok }
    end
  end
   
  def add_author
    @authors = AuthenticatedSystem::Person.order('fullname')
  end     
  
  def contract
    @d = Description.find(params[:id])
    @description =  nil
  end # contract.js.erb
  
  def expand
    @d = Description.find(params[:id])
    @description =  Description.find(params[:id])
  end # expand.js.erb
  
  private
  # This is tied to categories
  def find_category
    @category = Category.find(params[:category_id])
	  @main_category = @category.application_root
  end
    
  def description_url(description)
    category_description_url(@category, description)
  end    
end

app/helpers/descriptions_helper.rb
module DescriptionsHelper
end

app/views/descriptions/_authors_selector.erb
<div class="dropdown">
<p>
<%= select_tag 'description[author_ids][]', options_for_select(@authors.collect{|a| [ a.fullname , a.id] }, selected.nil? ? nil : selected) %>
<%= link_to_function 'remove', "this.up('.dropdown').remove()" %>
</p>
</div>

app/views/descriptions/_authors_selector.html.erb
<div class="dropdown">
<p>
<%= select_tag 'description[author_ids][]', options_for_select(@authors.collect{|a| [ a.fullname , a.id] }, selected.nil? ? nil : selected) %>
<%= link_to_function ts(:remove), "$(this).parents('.dropdown:first').remove()" %>
</p>
</div>

app/views/descriptions/_contracted.html.erb
<%= form_tag edit_category_description_path(category, d), :remote => true, :method => :get do %>
      <h2 class="description_title">
<%      authors = d.authors
        language = d.language %>
<%=     link_to '&nbsp;'.html_safe, expand_category_description_path(category,d), :remote => true, :class => 'descriptionplus_icon' %>
<%=     d.title.blank? ? Description.model_name.human.titleize.s : h(d.title) %>
      </h2>
      <p>by
	    <span class='content_by'><%= authors.empty? ? category.creator.screen_name : join_with_and(d.authors.collect{|a| a.fullname}) %></span>
	    (<%= "#{h(language.title.s)}, " if language != ComplexScripts::Language.find_by_locale(I18n.locale) %><%= ts('update.d.record', :when => h(d.updated_at.to_date.to_formatted_s(:long))) %>)
      </p>
      <p>
<%      if authorized? hash_for_edit_category_description_path %>
<%=       submit_tag 'edit description' %>
<%      end %>
      </p>
<%  end %>

app/views/descriptions/_edit.html.erb
<h1><%= ts :in, :what =>t(:for, :what => t('edit.ing.record', :what => Description.model_name.human.titleize), :whom => "<em>#{h(@category.title)}</em>"), :where => h(@description.language.title) %></h1>
<%= error_messages_for :description %>
<%= form_for(:description, :url => category_description_path(@category, @description), :remote => true, :method => :put, :html => { :id => 'description_form' }) do |f| %>
<%=   render :partial => 'form', :locals => {:f => f, :default_author_id => nil} %>
      <p><%= globalized_submit_tag 'update.this' %></p>
<%  end %>
<%= javascript_tag("$(\'#description_form\').bind(\'ajax:beforeSend\', function(){ tinyMCE.triggerSave();});") %>
<p>
<%  if authorized? hash_for_category_description_path(:action => 'destroy') %>
<%=   link_to ts('delete.this'), category_description_path(@category, @description), :confirm => 'Are you sure?', :remote => true, :method => :delete %> |
<%  end %>
<%= link_to ts('cancel.this'), category_child_path(@main_category, @category), :remote => true %>
</p>

app/views/descriptions/_expanded.html.erb
<h2 class="description_title">
<%  authors = d.authors
    language = d.language %>
<%= link_to '&nbsp;'.html_safe, contract_category_description_path(category,d), :remote => true, :class => 'descriptionminus_icon' %>
<%= d.title.blank? ? Description.model_name.human.titleize.s : h(d.title) %>
</h2>
<p>
  by
  <span class='content_by'><%= authors.empty? ? category.creator.screen_name : author_str = join_with_and(d.authors.collect{|a| a.fullname}) %></span>
  (<%= "#{h(language.title.s)}, " if language != ComplexScripts::Language.find_by_locale(I18n.locale) %><%= ts('update.d.record', :when => h(d.updated_at.to_date.to_formatted_s(:long))) %>)
</p>
<p>
<%= d.content.html_safe %>
</p>
<%  if !d.sources.empty? %>
      <div id='descsources_div' class='padded'>
<%=     render :partial => 'sources/index', :locals => {:resource => d, :category => category} %>
      </div>
<%  end %>
<p><div class='padded'>
<%= form_tag new_category_description_source_path(category,d), :remote => true, :method => :get do %>
<%    if authorized? hash_for_new_category_description_source_path %>
<%=     submit_tag te('add.record', :what => Source.model_name.human) %>
<%    end 
    end %>
</div></p>
<%= form_tag edit_category_description_path(category, d), :remote => true, :method => :get do %>
    <p>
<%    if authorized? hash_for_edit_category_description_path %>
<%=     submit_tag te('edit.record', :what => Description.model_name.human) %>
<%    end %>
    </p>
<% end %>

app/views/descriptions/_form.html.erb
<%= tagged_tinymce_script %>
<p>
    <b><%= ts :for, :what => ComplexScripts::Language.model_name.human.titleize, :whom => Description.model_name.human.titleize %></b><br />
<%= f.select(:language_id, @languages.collect {|l| [ h(l.title), l.id ] }, { :include_blank => false }) %>
</p>
<p>
  <b><%= Description.human_attribute_name('title').s %></b><br />
	<%= f.text_field :title, :size => 50 %>
</p>
<p>
    <b><%= Description.human_attribute_name('description').s %></b><br />
<%= f.text_area :content, :rows => 16, :cols => 40, :class => 'mceEditor' %>
</p>
<%= f.hidden_field :category_id %>
<p>
<%= link_to ts('add.record', :what => t('new.record', :what => Description.human_attribute_name(:author))), add_author_category_descriptions_path(@category), :remote => true %>
</p>
<div id="authors_div">
<% if default_author_id.nil? %>
<%   for author in @description.authors %>
<%=    render :partial => 'authors_selector', :locals => {:selected => author.id} %>
<%   end
   else %>
<%=  render :partial => 'authors_selector', :locals => {:selected => default_author_id} %>
<% end %>
</div>    
<div id="update_div"/>

app/views/descriptions/_index.html.erb
<%  category.descriptions.order('is_main DESC').each do |d| %>
	<div id="<%= "#{d.id}_descdiv" %>">
<%  if @description.nil? 		
      if d.is_main? %>
		<%=   render :partial => 'descriptions/expanded', :locals => {:category => category, :d => d} %>
<%	  else %>
		<%=   render :partial => 'descriptions/contracted', :locals => {:category => category, :d => d} %>
<%    end
    else
      if d == @description %>
<%=     render :partial => 'descriptions/expanded', :locals => {:category => category, :d => d} %>
<%	  else %>
<%=     render :partial => 'descriptions/contracted', :locals => {:category => category, :d => d} %>
<%    end
    end %>
    </div>
<%  end %>

app/views/descriptions/_new.html.erb
<h1><%= ts :for, :what => Description.model_name.human.capitalize, :whom => "<em>#{h(@category.title)}</em>" %></h1>
<%= error_messages_for :description %>
<%= form_for(:description, :url => category_descriptions_path(@category), :html => { :id => 'description_form' }) do |f| %>
<%   if session[:default_author_id].nil?
	   person = current_user.person
 	   default_author_id = person.nil? ? nil : person.id
     else
       default_author_id = session[:default_author_id]
	 end %>
<%=  render :partial => 'form', :locals => {:f => f, :default_author_id => default_author_id} %>
     <p>
<%=    submit_tag te('creat.e.record', :what => Description.model_name.human.capitalize), language_options(:disable_with => 'Processing...') %>
     </p>
<% end %>
<%= javascript_tag("$(\'#description_form\').bind(\'ajax:beforeSend\', function(){ tinyMCE.triggerSave();});") %>
<p>
<%= link_to ts('cancel.this'), category_child_path(@main_category, @category), :remote => true %>
</p>

app/views/descriptions/add_author.js.erb
$("#update_div").before("<%= escape_javascript(render(:partial => 'authors_selector', :locals => {:selected => nil})) %>")

app/views/descriptions/contract.js.erb
$("#<%= @d.id %>_descdiv").html("<%= escape_javascript(render(:partial => 'contracted', :locals => {:category => @category, :d => @d})) %>")

app/views/descriptions/edit.html.erb
<%= render :partial => 'edit' %>

app/views/descriptions/expand.js.erb
$("#descriptions_div").html("<%= escape_javascript(render(:partial => 'descriptions/index', :locals => {:category => @category, :d => @d})) %>")

app/views/descriptions/new.html.erb
<%= render :partial => 'new' %>

app/views/descriptions/new.js.erb
$("#info").html("<%= escape_javascript(render(:partial => 'new')) %>")