config/routes.rb
Rails.application.routes.draw do
  resources :blurbs
  resources :pop_up_categories do
    member do
      get :contract
      get :expand
    end
  end
  resources :categories do
    collection do
      get :list_with_features
      get :list_with_shapes
      get :list
      get :all
      get :add_curator
      get :all_with_features
      get :all_with_shapes
      match '/by_title/:title.:format' => 'categories#by_title'
    end
    member do
      get :list_with_features
      put :update_primary_description
      get :list_with_shapes
      get :detailed
      get :set_primary_description
      get :list
      get :all
      get :all_with_features
      get :all_with_shapes
      get :modify_title
    end
    resources :children, :controller => 'categories' do
      collection do
        get :add_curator
      end
      member do
        get :contract
        get :expand
        get :modify_title
        get :expanded
        get :contracted
      end
    end
    resources :iframe, :controller => 'categories' do
      collection do
        get :add_curator
      end
      member do
        get :contract
        get :expand
        get :modify_title
      end
    end
    resources :translated_titles do
      collection do
        get :add_author
      end    
    end
    resources :descriptions do
      collection do
        get :add_author
      end
      member do
        get :contract
        get :expand
      end
      resources :sources do
        member do
          get :contract
          get :expand
        end
        resources :translated_sources do
          collection do
            get :add_author
          end
        end
      end
    end
    resources :sources do
      member do
        get :contract
        get :expand
      end
      resources :translated_sources do
        collection do
          get :add_author
        end     
      end
    end
  end
  root :to => 'home#index'
  resources :places, :only => 'show'
  resources :media, :only => 'show', :path => 'media_objects'
  # match '/:controller(/:action(/:id))'
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  title      :string(255)      not null
#  parent_id  :integer
#  creator_id :integer          not null
#  created_at :datetime
#  updated_at :datetime
#  published  :boolean          default(FALSE), not null
#  cumulative :boolean          default(TRUE), not null
#

class Category < ActiveRecord::Base
  attr_accessible :title, :parent_id, :published, :cumulative, :curator_ids
  
  validates_presence_of :title, :creator_id
  belongs_to :creator, :class_name => 'AuthenticatedSystem::User', :foreign_key => 'creator_id'
  #belongs_to :curator, :class_name => 'AuthenticatedSystem::Person', :foreign_key => 'curator_id'
  has_and_belongs_to_many :curators, :class_name => 'AuthenticatedSystem::Person', :join_table => 'categories_curators', :association_foreign_key => 'curator_id'
  has_many :translated_titles, :dependent => :destroy
  has_many :descriptions, :dependent => :destroy
  has_many :sources, :as => :resource 
  acts_as_tree :order => 'title' if Category.table_exists?
  include Tree
  
  def published_children
    self.children.where(:published => true).order('title')
  end
  
  def self.application_roots
    self.where(:parent_id => ApplicationSettings.application_root_id).order('title')
  end
  
  def application_root
    node = self
    application_root_id = ApplicationSettings.application_root_id
    node = node.parent while !node.parent_id.nil? && node.parent_id != application_root_id
    node
  end
  
  def self.published_roots
    self.application_roots.where(:published => true).order('title')
  end

  def self.published_roots_and_descendants
    self.published_roots.inject([]){ |descendants, root| descendants.concat(root.self_and_descendants) }
  end
  
  def children_with_descendants
    stack = [self] + children.collect { |c| c }
    result = []
    while !stack.empty?
      child = stack.pop
      result << [child.full_lineage(10), child.id]
      child.children.each {|c| stack.push c }
    end
    result
  end

  def self_and_descendants
    [self] + children.collect{|c| c.self_and_descendants}
  end
    
  def media_count(options = {})
    media_count_hash = Rails.cache.fetch("#{self.cache_key}/media_count", :expires_in => 1.day) do
      media_category_count = MmsIntegration::MediaCategoryCount.find(:all, :params => {:category_id => self.id}).dup
      media_count_hash = { 'Medium' => media_category_count.shift.count.to_i }
      media_category_count.each{|count| media_count_hash[count.medium_type] = count.count.to_i }
      media_count_hash
    end
    type = options[:type]
    return type.nil? ? media_count_hash['Medium'] : media_count_hash[type]
  end
  
  def mediabase_count
    m = MediabaseCategoryCount.find(self.id)
    return 0 if m.nil?
    return m[:kmap_count].to_i
  end
  
  def feature_count
    Rails.cache.fetch("#{self.cache_key}/feature_count", :expires_in => 1.day) do
      PlacesIntegration::FeatureCategoryCount.find(:all, :params => {:category_id => self.id}).first.count
    end
  end
  
  def shape_count
    Rails.cache.fetch("#{self.cache_key}/shape_count", :expires_in => 1.day) do
      PlacesIntegration::FeatureCategoryCount.find(:all, :params => {:category_id => self.id}).first.count_with_shapes
    end
  end
  
  def mediabase_url
    m = MediabaseCategoryCount.find(self.id)
    return nil if m.nil?
    return "#{MediabaseResource.site.to_s}/#{m[:view_uri]}"
  end
  
  def media_url
    MediaManagementResource.get_url + topic_path
  end

  def pictures_url
    MediaManagementResource.get_url + topic_path('pictures')
  end

  def videos_url
    MediaManagementResource.get_url + topic_path('videos')
  end

  def documents_url
    MediaManagementResource.get_url + topic_path('documents')
  end
  
  def places_url
    PlacesIntegration::PlacesResource.get_url + topic_path
  end
  
  alias :kmaps_url :places_url  
  
  def self.find_all_by_feature_id(feature_id)
    PlacesIntegration::Feature.find(feature_id).feature_type_ids.collect{|id| Category.find(id)}
  end
  
  def self.find_all_by_medium_id(medium_id)
    MmsIntegration::Medium.find(medium_id).category_ids.collect{|id| Category.find(id)}
  end
  
  def self.human_name(*args)
    self.model_name.human(*args)
  end
  
  private
  
  def topic_path(type = nil)
    a = ['topics', self.id]
    a << type if !type.nil?
    a.join('/')
  end
end

app/controllers/categories_controller.rb
class CategoriesController < AclController
  before_filter :find_main_category
  helper :pop_up_categories
  caches_page :index, :show, :detailed, :all, :all_with_features, :all_with_shapes, :list, :list_with_features, :list_with_shapes, :if => Proc.new { |c| c.request.format.json? || c.request.format.xml? }
  cache_sweeper :category_sweeper, :only => [:create, :update, :destroy]
  helper :sources
  
  def initialize
    super
    @guest_perms += [ 'categories/all', 'categories/all_with_features', 'categories/all_with_shapes', 'categories/by_title', 'categories/contract', 'categories/expand', 'categories/contracted', 'categories/expanded', 'categories/iframe', 'categories/list', 'categories/list_with_features', 'categories/list_with_shapes', 'categories/detailed']
  end
  
  
  # GET /categories
  # GET /categories.xml
  def index
    if @main_category.nil?
      @categories = logged_in? ? Category.application_roots : Category.published_roots
      @tab_options ||= {}
      @tab_options[:entity] = Category.find(session[:current_category_id]) unless session[:current_category_id].blank?
    else
      @tab_options ||= {}
      @tab_options[:entity] = @main_category
      session[:current_category_id] = @main_category.id
      @categories = logged_in? ? @main_category.children : @main_category.published_children
    end
    respond_to do |format|
      format.html do # index.html.erb
        if @main_category.nil?
          render :action => 'main_index'
        else
          @current_tab_id = :topics
          render :action => 'index', :layout => 'multi_column'
        end
      end
      format.xml do 
  		  @categories.each do |cat|
  		    cat['parent_id'] = nil if ApplicationSettings.application_root_id==cat.parent_id
  		    cat['children_count'] = cat.children.length
		    end
      	render :xml => @categories
      end
      format.json { render :json => @categories.to_json }
      format.csv do
        if @main_category.nil?
          descendant_ids = @categories.collect(&:id)
        else
          descendant_ids = @main_category.descendants
        end
        @languages = ComplexScripts::Language.find_by_sql(['SELECT DISTINCT languages.* FROM languages, translated_titles WHERE translated_titles.language_id = languages.id AND translated_titles.category_id IN (?) ORDER BY languages.title', descendant_ids])
      end
    end
  end

  # GET /categories/1
  # GET /categories/1.xml
  def show
    @category = Category.find(params[:id])
    @current_tab_id = :topics
    @tab_options ||= {}
    @tab_options[:entity] = @category
    session[:current_category_id] = @category.id
    respond_to do |format|
      format.html do
        pu = params[:parent_url]
        if @main_category.nil?
          #render :action => 'main_show'
          redirect_to category_child_url(@category.application_root, @category) << ( pu.nil? ? '' : "?parent_url=" << pu )
        else # show.html.erb
          if @category == @main_category
            redirect_to category_children_url(@main_category) << ( pu.nil? ? '' : "?parent_url=" << pu )
          else
            @ancestors_for_current = @category.ancestors.collect{|c| c.id}
            @ancestors_for_current << @category.id
            @categories = logged_in? ? @main_category.children : @main_category.published_children
            # This isn't terribly clean. See routes.rb for a comment about iframe routing.
            if request.fullpath =~ /\/iframe\//
              render :action => 'iframe', :layout => 'iframe'
            else
              render :action => 'show', :layout => 'multi_column'
            end
          end
        end
      end
      format.js { render 'show' }
      format.xml do
        @category['parent_id'] = nil if ApplicationSettings.application_root_id==@category.parent_id
        @category['children_count'] = @category.children.size
      	render :xml => @category
      end
      format.json  { render :json => @category.to_json }
    end
  end

  # GET /categories/new
  # GET /categories/new.xml
  def new
    @category = Category.new
    @curators = AuthenticatedSystem::Person.order('fullname')
    if @main_category.nil?
      @category.parent_id = ApplicationSettings.application_root_id
      @category.published = false
      if session[:default_curator_id].nil?
        person = current_user.person
        session[:default_curator_id] = person.id if !person.nil?
      end
      respond_to do |format|
        format.html { render :action => 'main_new' }
        format.xml  { render :xml => @category }
      end      
    else
      @category.published = true
      parent_id = params[:parent_id]
      if !parent_id.blank?
        parent = Category.find(parent_id)
      else
        parent = @main_category
      end
      @category.parent = parent
      respond_to do |format|
        format.html do
          @ancestors_for_current = @category.ancestors.collect{|c| c.id}
          @ancestors_for_current << @category.id
          @categories = @main_category.children
          render :action => 'new', :layout => 'multi-column'
        end
        format.js # render new.js.erb
        format.xml  { render :xml => @category }
      end      
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
    @curators = AuthenticatedSystem::Person.order('fullname')
    respond_to do |format|
      format.html do
        if @main_category.nil?
  		    @main_category = @category
          @ancestors_for_current = @category.ancestors.collect{|c| c.id}
          @ancestors_for_current << @category.id
          @categories = @main_category.children
        	render :action => 'main_edit', :layout => 'multi_column'
  		    # render :action => 'main_edit'
        else # edit.html.erb
          @ancestors_for_current = @category.ancestors.collect{|c| c.id}
          @ancestors_for_current << @category.id
          @categories = @main_category.children
          render :action => 'edit', :layout => 'multi_column'
        end
      end
      format.js # edit.js.erb
    end
  end

  # POST /categories
  # POST /categories.xml
  def create
    @category = Category.new(params[:category])
    @category.creator = current_user
    if @category.save
      curators = @category.curators
      session[:default_curator_id] = curators.first.id if curators.size==1
      category_title = @main_category.nil? ? Category.model_name.human.capitalize : @main_category.title.titleize      
      respond_to do |format|
        format.js do
          if @main_category.nil?
            @categories = []
            @ancestors_for_current = nil
          else
            @categories = @main_category.children
            @ancestors_for_current = @category.ancestors.collect{|c| c.id}
            @ancestors_for_current << @category.id
          end
        end # render 'create'
        format.html do 
        	flash[:notice] = ts 'new.successful', :what => category_title
          if @main_category.nil?
            redirect_to category_children_url(@category)
          else
            redirect_to category_child_url(@main_category, @category)
          end
        end
        format.xml  { render :xml => @category, :status => :created, :location => @category }
      end
    else
      @curators = AuthenticatedSystem::Person.order('fullname')
      respond_to do |format|
        format.js { render 'new' }
        format.html do
          if @main_category.nil?
            render :action => 'main_new'
          else
            render :action => 'new', :layout => 'multi-column'
          end
        end
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.xml
  def update
    params_category = params[:category]
    params_category[:curator_ids] ||= [] if !params_category.nil?
    @category = Category.find(params[:id])
    if !params[:primary].nil?
      @primary = Category.find(params[:primary])
      @category.descriptions.update_all("is_main = 0")
      @category.descriptions.update_all("is_main = 1","id=#{@primary.id}")
    end
    @curators = AuthenticatedSystem::Person.order('fullname')
    parent = @category.parent
    if @category.update_attributes(params_category)
	    @category.reload
      @new_parent = @category.application_root
      category_title = @main_category.nil? ? Category.model_name.human.capitalize : @main_category.title.titleize
      flash[:notice] = ts 'edit.successful', :what => category_title
      respond_to do |format|
        format.html do
          @main_category = @new_parent if @main_category.nil? && !@new_parent.nil?
          if @main_category.nil?
            redirect_to category_url(@category)
          else
            redirect_to category_child_url(@main_category, @category)
          end
        end
        format.js do
          if @main_category.nil?
            @categories = []
            @ancestors_for_current = nil
          else
            @categories = @main_category.children
            @ancestors_for_current = @category.ancestors.collect{|c| c.id}
            @ancestors_for_current << @category.id
          end
        end   # update.js.erb
        format.xml  { head :ok }
      end    	
    else
      respond_to do |format|
        format.html do
          if @main_category.nil?
            render 'main_edit'
          else
            render 'edit', :layout => 'multi_column'
          end
        end
        format.js   { render 'edit' }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end      
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.xml
  def destroy
    @category = Category.find(params[:id])
    @title = @category.title
    @parent = @category.parent
    @category.destroy
    respond_to do |format|
      format.html do
        if @main_category.nil?
          redirect_to root_url
        else

app/helpers/categories_helper.rb
module CategoriesHelper 
end

app/views/categories/_curators_selector.erb
<div class="dropdown">
<p>
<%= select_tag 'category[curator_ids][]', options_for_select(@curators.collect{|a| [ a.fullname , a.id] }, selected.nil? ? nil : selected) %>
<%= link_to_function 'remove', "this.up('.dropdown').remove()" %>
</p>
</div>

app/views/categories/_expanded.html.erb
<%  children = logged_in? ? expanded.children : expanded.published_children
    has_no_children = children.empty?
    if has_no_children %>
      <span class="node-empty"></span>
<%  else 
      link_id = "contracted_#{expanded.id}_link" %>
<%=   link_to '', contracted_category_child_path(@category.nil? ? @main_category.id : @category.id, expanded.id, :main_category_id => @main_category.id), :remote => true, :class => 'node-minus', :id => link_id %>
<%=   javascript_tag("$(\'##{link_id}\').bind(\'ajax:complete\', function(){ $(\'node_#{@category.nil? ? @main_category.id : @category.id}_div > .node-name\').addClassName(\'selected-node\'); });") %>
<%  end %>
<%= render :partial => 'selectable_node', :locals => { :node => expanded } %>
<%  if base_language? && authorized?(hash_for_new_category_child_path)
	  options = { :remote => true }
      options[:class] = 'unpublished' if !expanded.published? %>
      (<%= link_to ts('new.record', :what => t(:subcategory)), new_category_child_path(@main_category, :parent_id => expanded), options %>)
<%  end %>
<%= render :partial => 'index', :locals => {:node => expanded, :categories => children} %>

app/views/categories/_form.html.erb
<p><b><%= ts 'name.in', :what => t('language.english') %></b><br />
<%= f.text_field :title, :size=>60 %>
</p>
<% if !changing_parent_allowed %>
<%=  f.hidden_field :parent_id %>
<% else %>
     <p><b><%= ts 'parent.of', :who => Category.model_name.human %></b><br />
<%=    category_selector(:category, :parent) %>
     </p>
<% end %>
<p><b><%= Category.human_attribute_name(:published).s %></b>&nbsp;
<%= f.radio_button :published, "true" %> <%= f.label :published, ts(:affirmation) %>&nbsp;
<%= f.radio_button :published, "false" %> <%= f.label :unpublished, ts(:negation) %>  
</p>
<p><b><%= Category.human_attribute_name(:cumulative).s %></b>&nbsp;
<%= f.radio_button :cumulative, "true" %> <%= f.label :cumulative, ts(:affirmation) %>&nbsp;
<%= f.radio_button :cumulative, "false" %> <%= f.label :noncumulative, ts(:negation) %>  
</p>
<p>
<%= link_to ts('add.record', :what => t('new.record', :what => Category.human_attribute_name(:curator)).downcase), add_curator_categories_path, :remote => true %>
</p>
<div id="curators_div">
<% if default_curator_id.nil?
     for curator in @category.curators %>
<%=    render :partial => 'curators_selector', :locals => {:selected => curator.id} %>   
<%   end 
   else 
     if @main_category.nil? %>
<%=    render :partial => 'curators_selector', :locals => {:selected => default_curator_id} %>
<%   end
   end %>
</div>
<div id="update_div"></div>

app/views/categories/_info.html.erb
<%  if !category.curators.empty? %>
<%=   display_if_not_blank ts('by.curated'), "<i>#{join_with_and(category.curators.collect{|c| c.fullname}) if !category.curators.empty?}</i>" %>
<%  end
    if logged_in? 
      user = category.creator 
      screen_name = user.screen_name 
	  person = user.person %>
<%=	  display_if_not_blank ts('by.entered'), "#{person.nil? ? screen_name : link_to(h(screen_name), authenticated_system_person_user_path(person))} (#{ts('update.d.record', :when => h(category.updated_at.to_date.to_formatted_s(:long)))})" %>
<%  end
    if !category.sources.empty? %>
      <div id='catsources_div' class='padded'>
<%=     render :partial => 'sources/index', :locals => {:resource => category} %>
      </div>
<%  end %>
<p><div class='padded'>
<%= form_tag new_category_source_path(category), :method => :get, :remote => true do %>
<%    if authorized? hash_for_new_category_source_path %>
<%=     submit_tag te('add.record', :what => Source.model_name.human) %>
<%    end 
    end %>
</div></p>
<%  if !category.descriptions.empty? %>
      <div id='descriptions_div' class='descriptions_div'>
<%=     render :partial => 'descriptions/index', :locals => {:category => category} %>
      </div>
<%    if !category.descriptions.empty? && authorized?(hash_for_set_primary_description_category_path) %>
        <p><%= link_to ts('primary_description.set'), set_primary_description_category_path(category), :remote => true %></p>
<%    end
    end
    associated_resources = [
      ['Places', category.feature_count, category.places_url],
      ['Pictures', category.media_count(:type => 'Picture'), category.pictures_url],
      ['Video', category.media_count(:type => 'Video'), category.videos_url],
      ['Texts', category.media_count(:type => 'Document'), category.documents_url],
      ['Audio & Video', category.mediabase_count, category.mediabase_url]
    ]
    if associated_resources.collect{|ar| ar[1]}.sum > 0 %>
    <div class="descriptions_div">
      <h3 class="description_title">Associated Resources</h3>
    </div>
    <ul class="main_list normal">
<%    options = {}
      resource_link_target = ApplicationSettings.resource_link_target
      options[:target] = resource_link_target if !resource_link_target.blank? %>
<%=    associated_resources.reject{|ar| ar[1] == 0}.collect{|ar| "<li>#{link_to("#{ar[0]} (#{ar[1]})", ar[2], options)}</li>"}.join.html_safe %>
    </ul><br/>
<%  end
    if authorized? hash_for_new_category_description_path %>
      <p>
<%=     form_tag new_category_description_path(category), :method => :get, :remote => true do %>
<%=       submit_tag te('add.record', :what => Description.model_name.human) %>
<%      end %>
      </p>
<%  end %>

app/views/categories/_title.html.erb
<% if @main_category.nil? %>
  <h1><%= ts 'edit.ing.record', :what => t('name.for', :what => t('topical_map.this', :count => 1)) %></h1>
<% else
     master = (@main_category == @category.parent) %>
     <h1><%= ts 'edit.ing.record', :what => t('name.for', :what => master ? t(:master, :what => Category.model_name.human.capitalize) : t(:subcategory)) %></h1>
<% end %>
<%= error_messages_for :category %>
<% if base_language? %>
<%=  form_for(:category, :url => @main_category.nil? ? category_path(@category) : category_child_path(@main_category, @category), :remote => true, :method => :put, :html => { :id => 'category_form' }) do |f| %>
       <p><b><%= ts 'name.in', :what => t('language.english') %></b><br />
<%=      f.text_field :title %>
       </p>
       <p><%= globalized_submit_tag 'update.this' %></p> 
<%   end %>
<% end %>
<p><%= link_to ts('cancel.record', :what => t('edit.ing.this')), @main_category.nil? ? category_path(@category) : category_child_path(@main_category, @category), :remote => true %></p>

app/views/categories/contract.js.erb
$("#node_<%= @category.id %>_div").html("<%= escape_javascript(render(:partial => 'contracted', :object => @category, :locals => {:margin_depth => @margin_depth})) %>")

app/views/categories/contracted.js.erb
$("#node_<%= @node.id %>_div").html("<%= escape_javascript(render(:partial => 'contracted', :locals => { :contracted => @node })) %>")

app/views/categories/index.csv.erb
<%= CSV.generate_line ['id', 'Category Title'] + @languages.collect(&:title) %>
<%= render :partial => 'index', :locals => {:category => @main_category, :categories => @categories, :margin_depth => 0} %>

app/views/categories/list.html.erb
<h2><%= Category.model_name.human(:count => @categories.size).titleize %> Associated with <%= @object_title.s %></h2>
<ul class='main_list'>
<% for category in @categories do %>
     <li class="normal"><%= link_to h(category.title), category_child_path(category.application_root, category) %></li>
<% end %>
</ul>
<br />
<p><%= link_to ts(:in, :what => @object_title, :where => @object_type), @object_url %></p>

app/views/categories/main_edit.html.erb
<div id="container-wrapper">
  <div id="container-right-5050" class="container-right-5050">
	<div class="shell-2">
      <h1><%= ts 'topical_map.for', :what => h(@main_category.title.titleize) %></h1>
<%    if base_language? && authorized?(hash_for_new_category_child_path) %>
<%=     form_tag new_category_child_path(@main_category), :remote => true, :method => :get do %>
<%=       submit_tag ts('new.record', :what => t(:master, :what => Category.model_name.human.capitalize)) %>
<%      end
      end %>
      <div id="navigation" class="normal">
<%=     render :partial => 'index', :locals => {:margin_depth => 0, :categories => @categories} %>
      </div>
      <p>&nbsp;</p>
<%=   render :partial => 'persistent_links' %>
    </div>
  </div>
  <div id="container-left-5050" class="container-left-5050">
    <div class="shell-2">
      <div id="info">
<%=     render :partial => 'main_edit' %>
      </div>
    </div>
  </div>
</div>

app/views/categories/main_new.html.erb
<h1><%= ts 'new.record', :what => t('topical_map.this', :count => 1) %></h1>
<%= error_messages_for :category %>
<%= form_for(@category) do |f| %>
<%=  render :partial => 'form', :locals => {:changing_parent_allowed => false, :f => f, :default_curator_id => session[:default_curator_id]} %>
    <p>
<%=  globalized_submit_tag 'creat.e.this' %>
    </p>
<% end %>
<p><%= link_to ts('cancel.this'), root_path %></p>

app/views/categories/set_primary_description.js.erb
$("#info").html("<%= escape_javascript(render(:partial => 'primary_selector')) %>")

app/views/categories/show.html.erb
<div id="container-right-5050" class="container-right-5050">
  <div class="shell-2">
    <h1><%= ts 'topical_map.for', :what => h(@main_category.title) %></h1>
<%  if base_language? && authorized?(hash_for_new_category_child_path) %>
<%=   form_tag new_category_child_path(@main_category), :remote => true, :method => :get do %>
<%=     submit_tag ts('new.record', :what => t(:master, :what => Category.model_name.human.capitalize)) %>
<%    end
    end %>
    <div id="navigation" class="normal">
<%=   render :partial => 'index', :locals => {:margin_depth => 0, :categories => @categories} %>
	</div>
	<p>&nbsp;</p>
<%= render :partial => 'persistent_links' %>
  </div>
</div>
<div id="container-left-5050" class="container-left-5050">
  <div class="shell-2">
    <div id="info">
<%=   render :partial => 'show' %>
    </div>
  </div>
</div>

app/views/categories/tree.js.erb
<% categories = logged_in? ? @main_category.children : @main_category.published_children
   @ancestors_for_current = @category.ancestors.collect{|c| c.id}
   @ancestors_for_current << @category.id %>
$("#navigation").html("<%= escape_javascript(render(:partial => 'index', :locals => {:margin_depth => 0, :categories => categories})) %>")